package com.balaji.compose.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF6F43C0)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFEBDDFF)
val onPrimaryContainerLight = Color(0xFF250059)
val secondaryLight = Color(0xFF635B70)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE9DEF8)
val onSecondaryContainerLight = Color(0xFF1F182B)
val tertiaryLight = Color(0xFF7E525D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD9E1)
val onTertiaryContainerLight = Color(0xFF31101B)
val errorLight = Color(0xFFBA1A1A)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorLight = Color(0xFFFFFFFF)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFFBFF)
val onBackgroundLight = Color(0xFF1D1B1E)
val surfaceLight = Color(0xFFFFFBFF)
val onSurfaceLight = Color(0xFF1D1B1E)
val surfaceVariantLight = Color(0xFFE7E0EB)
val onSurfaceVariantLight = Color(0xFF49454E)
val outlineLight = Color(0xFF7A757F)
val inverseOnSurfaceLight = Color(0xFFF5EFF4)
val inverseSurfaceLight = Color(0xFF323033)
val inversePrimaryLight = Color(0xFFD3BBFF)
val shadowLight = Color(0xFF000000)
val surfaceTintLight = Color(0xFF6F43C0)
val outlineVariantLight = Color(0xFFCBC4CF)
val scrimLight = Color(0xFF000000)

val primaryDark = Color(0xFFD3BBFF)
val onPrimaryDark = Color(0xFF3F008D)
val primaryContainerDark = Color(0xFF5727A6)
val onPrimaryContainerDark = Color(0xFFEBDDFF)
val secondaryDark = Color(0xFFCDC2DB)
val onSecondaryDark = Color(0xFF342D40)
val secondaryContainerDark = Color(0xFF4B4358)
val onSecondaryContainerDark = Color(0xFFE9DEF8)
val tertiaryDark = Color(0xFFF0B7C5)
val onTertiaryDark = Color(0xFF4A2530)
val tertiaryContainerDark = Color(0xFF643B46)
val onTertiaryContainerDark = Color(0xFFFFD9E1)
val errorDark = Color(0xFFFFB4AB)
val errorContainerDark = Color(0xFF93000A)
val onErrorDark = Color(0xFF690005)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1D1B1E)
val onBackgroundDark = Color(0xFFE6E1E6)
val surfaceDark = Color(0xFF1D1B1E)
val onSurfaceDark = Color(0xFFE6E1E6)
val surfaceVariantDark = Color(0xFF49454E)
val onSurfaceVariantDark = Color(0xFFCBC4CF)
val outlineDark = Color(0xFF948F99)
val inverseOnSurfaceDark = Color(0xFF1D1B1E)
val inverseSurfaceDark = Color(0xFFE6E1E6)
val inversePrimaryDark = Color(0xFF6F43C0)
val shadowDark = Color(0xFF000000)
val surfaceTintDark = Color(0xFFD3BBFF)
val outlineVariantDark = Color(0xFF49454E)
val scrimDark = Color(0xFF000000)


val seed = Color(0xFF673AB7)